#!\bin\bash

#adb uninstall co.colombiaapps.vpeclientes
rm AppNegocios.apk
ionic cordova build android --prod --release
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore colombiaapps.keystore platforms\android\app\build\outputs\apk\release\app-release-unsigned.apk jorgemoreno
rm AppNegocios.apk
echo colombiaApps2016
C:\Users\OEM\AppData\Local\Android\Sdk\build-tools\25.0.0\zipalign -v 4 platforms\android\app\build\outputs\apk\release\app-release-unsigned.apk AppNegocios.apk
#adb install App.apk
